// Code generated by proto watcher. DO NOT EDIT.

import 'package:libcli/src/command/command.dart' as command;

class GoogleProtoService extends command.Service {
  /// init googleProto service with predefine remote url
  /// remote url is defined in "service project/proto/.proto.json"
  /// For example:
  ///
  ///     GoogleProtoService service = GoogleProtoService();
  GoogleProtoService() : super('googleProto', 80, 10000, 20000);

  @override
  command.ProtoObject newObjectByID(int id, List<int> l) {
    switch (id) {
    }
    return null;
  }
}
