// Code generated by proto watcher. DO NOT EDIT.

import 'package:libcli/pb/pb.dart' as pb;
import 'ok.pb.dart';
import 'error.pb.dart';

  pb.Object objectBuilder(int id, List<int> bytes) {
    switch (id) {
      case 4:
        return OK.fromBuffer(bytes);
      case 5:
        return Error.fromBuffer(bytes);
    }
    throw Exception('failed to create object in commonObjectByID. id($id) out of range');
}
