// Code generated by proto watcher. DO NOT EDIT.

import 'package:libcli/pb/pb.dart' as pb;
import 'stub.pb.dart';

  pb.Object objectBuilder(int id, List<int> bytes) {
    switch (id) {
      case 1001:
        return Stub.fromBuffer(bytes);
    }
    throw Exception('failed to create object in commonObjectByID. id($id) out of range');
}
