// Code generated by proto watcher. DO NOT EDIT.

import 'package:libcli/pb/pb.dart' as pb;
import 'person.pb.dart';

  pb.Object objectBuilder(int id, List<int> bytes) {
    switch (id) {
      case 1001:
        return Person.fromBuffer(bytes);
    }
    throw Exception('failed to create object in sampleObjectByID. id($id) out of range');
}
