// Code generated by proto watcher. DO NOT EDIT.

import 'package:libcli/command.dart';
import 'package:libcli/pb.dart' as pb;
import 'geo-location.pb.dart';
import 'geo-locations.pb.dart';
import 'geo-suggestion.pb.dart';
import 'geo-suggestions.pb.dart';

class SysService extends Service {

  /// init sys service with predefine remote url
  /// remote url is defined in "service project/proto/.proto.json"
  /// For example:
  ///
  ///     SysService service = SysService();
  SysService(): super(serviceName: 'sys',timeout: 20000,slow: 10000);

  @override
  pb.Object newObjectByID(int id, List<int> l) {
    switch (id) {
      case 1004:
        return GeoLocation.fromBuffer(l);
      case 1005:
        return GeoLocations.fromBuffer(l);
      case 1006:
        return GeoSuggestion.fromBuffer(l);
      case 1007:
        return GeoSuggestions.fromBuffer(l);
    }
    throw Exception('failed to create object in SysService. id($id) out of range');
  }
}