// Code generated by proto watcher. DO NOT EDIT.

import 'package:libcli/command.dart';
import 'package:libpb/pb.dart' as pb;

class SysService extends Service {

  /// init sys service with predefine remote url
  /// remote url is defined in "service project/proto/.proto.json"
  /// For example:
  ///
  ///     SysService service = SysService();
  SysService(): super(serviceName: 'sys',timeout: 20000,slow: 10000);

  @override
  pb.Object newObjectByID(int id, List<int> l) {
    switch (id) {
    }
    throw Exception('failed to create object in SysService. id($id) out of range');
  }
}