// Code generated by proto watcher. DO NOT EDIT.

import 'package:libcli/command.dart';

class SysService extends Service {
  /// init sys service with predefine remote url
  /// remote url is defined in "service project/proto/.proto.json"
  /// For example:
  ///
  ///     SysService service = SysService();
  SysService()
      : super(
          serviceName: 'sys',
          timeout: 10000,
          slow: 20000,
        ) {
    //ignore error when report analytic to server
    errorHandler = (_) {};
  }

  @override
  ProtoObject newObjectByID(int id, List<int> l) {
    throw 'failed to create object in SysService. id ($id) out of range';
  }
}
