// Code generated by proto watcher. DO NOT EDIT.

import 'package:libcli/command.dart' as command;

class GoogleProtoService extends command.Service {
  /// init googleProto service with predefine remote url
  /// remote url is defined in "service project/proto/.proto.json"
  /// For example:
  ///
  ///     GoogleProtoService service = GoogleProtoService();
  GoogleProtoService()
      : super(
          serviceName: 'googleProto',
          timeout: 10000,
          slow: 20000,
        );

  @override
  command.ProtoObject newObjectByID(int id, List<int> l) {
    throw 'failed to create object in GoogleProtoService. cause id ($id) out of range';
  }
}
