// Code generated by proto watcher. DO NOT EDIT.

import 'package:libcli/command.dart' as command;
import 'package:libpb/pb.dart';
import 'echo_request.pb.dart';
import 'string_response.pb.dart';

class MockService extends command.Service {
  MockService()
      : super(
          serviceName: 'mock',
          timeout: 20000,
          slow: 10000,
        );

  @override
  ProtoObject newObjectByID(int id, List<int> l) {
    switch (id) {
      case 9001:
        return EchoAction.fromBuffer(l);
      case 1002:
        return StringResponse.fromBuffer(l);
    }
    throw 'failed to create object in MockService. id($id) out of range';
  }
}
