// Code generated by proto watcher. DO NOT EDIT.

import 'package:libcli/command.dart';
import 'package:libpb/src/pb/pb.dart' as pb;
import 'string-response.pb.dart';

class SampleService extends Service {

  /// init sample service with predefine remote url
  /// remote url is defined in "service project/proto/.proto.json"
  /// For example:
  ///
  ///     SampleService service = SampleService();
  SampleService(): super(serviceName: 'sample',timeout: 20000,slow: 10000);

  @override
  pb.Object newObjectByID(int id, List<int> l) {
    switch (id) {
      case 1002:
        return StringResponse.fromBuffer(l);
    }
    throw Exception('failed to create object in SampleService. id($id) out of range');
  }
}