// Code generated by proto watcher. DO NOT EDIT.

import 'package:libcli/command.dart' as command;
import 'package:libpb/pb.dart';
import 'package:libcli/mock/protobuf/command-echo.pb.dart';
import 'package:libcli/mock/protobuf/string-response.pb.dart';

class SampleService extends command.Service {
  SampleService()
      : super(
          serviceName: 'mock',
          timeout: 20000,
          slow: 10000,
        );

  @override
  PbObject newObjectByID(int id, List<int> l) {
    switch (id) {
      case 1003:
        return CommandEcho.fromBuffer(l);
      case 1004:
        return StringResponse.fromBuffer(l);
    }
    throw 'failed to create object in MockService. id($id) out of range';
  }
}
