// Code generated by proto watcher. DO NOT EDIT.

import 'package:libcli/command.dart' as command;
import 'echo_request.pb.dart';
import 'string_response.pb.dart';

class SysService extends command.Service {
  SysService() : super('sys', 20000, 10000);

  @override
  command.ProtoObject newObjectByID(int id, List<int> l) {
    switch (id) {
      case 9001:
        return EchoAction.fromBuffer(l);
      case 1002:
        return StringResponse.fromBuffer(l);
    }
    return null;
  }
}
