// Code generated by proto watcher. DO NOT EDIT.

import 'package:flutter/widgets.dart';
import 'package:provider/provider.dart';
import 'package:libcli/net/net.dart';


 /// SysService define sys service, source .proto can be found in /pb/sys
 ///
 ///     final service = SysService()..sender = (context, action) async {
 ///         return StringResponse()..value = 'fake';
 ///     };
 ///
 class SysService extends Service {
  SysService(): super('sys');

  /// of get SysService from context
  static SysService of(BuildContext context) {
    return Provider.of<SysService>(context, listen: false);
  }
}