// Code generated by proto watcher. DO NOT EDIT.

import 'package:libcli/pb/pb.dart' as pb;
import 'bool.pb.dart';
import 'error.pb.dart';
import 'number.pb.dart';
import 'ok.pb.dart';
import 'string.pb.dart';

pb.Object simpleObjectByID(int id, List<int> bytes) {
  switch (id) {
    case 1:
      return Bool.fromBuffer(bytes);
    case 2:
      return Error.fromBuffer(bytes);
    case 4:
      return Number.fromBuffer(bytes);
    case 5:
      return OK.fromBuffer(bytes);
    case 6:
      return String.fromBuffer(bytes);
  }
  throw Exception('failed to create object in simpleObjectByID. id($id) out of range');
}
