// Code generated by proto watcher. DO NOT EDIT.

import 'package:libcli/pb/pb.dart' as pb;
import 'bool.pb.dart';
import 'error.pb.dart';
import 'latlng.pb.dart';
import 'number.pb.dart';
import 'ok.pb.dart';
import 'string.pb.dart';

pb.Object typesObjectByID(int id, List<int> l) {
  switch (id) {
    case 1:
      return Bool.fromBuffer(l);
    case 2:
      return Error.fromBuffer(l);
    case 3:
      return Latlng.fromBuffer(l);
    case 4:
      return Number.fromBuffer(l);
    case 5:
      return OK.fromBuffer(l);
    case 6:
      return String.fromBuffer(l);
  }
  throw Exception('failed to create object in typesObjectByID. id($id) out of range');
}
