// Code generated by proto watcher. DO NOT EDIT.

import 'package:flutter/widgets.dart';
import 'package:provider/provider.dart';
import 'package:libcli/net/net.dart';


 /// AuthService define auth service, source .proto can be found in /pb/auth
 /// ```dart
 /// final service = AuthService()..sender = (context, action) async {
 ///     return StringResponse()..value = 'fake';
 /// };
 /// ```
 class AuthService extends Service {
  /// SysService create service with remote url
  AuthService(String url): super('auth', url);

  /// of get AuthService from context
  static AuthService of(BuildContext context) {
    return Provider.of<AuthService>(context, listen: false);
  }
}