// Code generated by proto watcher. DO NOT EDIT.

import 'package:libcli/command.dart';
import 'err.pb.dart';
import 'bool.pb.dart';
import 'num.pb.dart';
import 'text.pb.dart';

class SharedService extends Service {
  /// init shared service with predefine remote url
  /// remote url is defined in "service project/proto/.proto.json"
  /// For example:
  ///
  ///     SharedService service = SharedService();
  SharedService()
      : super(
          serviceName: 'shared',
          timeout: 10000,
          slow: 20000,
        );

  @override
  ProtoObject newObjectByID(int id, List<int> l) {
    switch (id) {
      case 0:
        return Err.fromBuffer(l);
      case 1:
        return Bool.fromBuffer(l);
      case 2:
        return Num.fromBuffer(l);
      case 3:
        return Text.fromBuffer(l);
    }
    throw 'failed to create object in SharedService. cause id ($id) out of range';
  }
}
