// Code generated by proto watcher. DO NOT EDIT.

import 'package:libcli/command.dart';
import 'err.pb.dart';
import 'num.pb.dart';
import 'ping_action.pb.dart';
import 'text.pb.dart';

class SharedService extends Service {

  /// init shared service with predefine remote url
  /// remote url is defined in "service project/proto/.proto.json"
  /// For example:
  ///
  ///     SharedService service = SharedService();
  SharedService(): super('shared',0,10000,20000);

  @override
  ProtoObject newObjectByID(int id, List<int> l) {
    switch (id) {
      case 1:
        return Err.fromBuffer(l);
      case 2:
        return Num.fromBuffer(l);
      case 4:
        return PingAction.fromBuffer(l);
      case 5:
        return Text.fromBuffer(l);
    }
    return null;
  }
}