// Code generated by proto watcher. DO NOT EDIT.

import 'package:libcli/command/command.dart';
import 'package:libcli/pb/pb.dart' as pb;
import 'geo-location.pb.dart';
import 'geo-locations.pb.dart';
import 'geo-suggestion.pb.dart';
import 'geo-suggestions.pb.dart';

pb.Object objectBuilder(int id, List<int> bytes) {
    switch (id) {
      case 1003:
        return GeoLocation.fromBuffer(bytes);
      case 1004:
        return GeoLocations.fromBuffer(bytes);
      case 1005:
        return GeoSuggestion.fromBuffer(bytes);
      case 1006:
        return GeoSuggestions.fromBuffer(bytes);
    }
    throw Exception('failed to create object in SysService. id($id) out of range');
}

class SysService extends Service {

  /// init sys service with predefine remote url
  /// remote url is defined in "service project/proto/.proto.json"
  /// For example:
  ///
  ///     SysService service = SysService();
  SysService(): super('sys');

  @override
  pb.Object newObjectByID(int id, List<int> bytes) => objectBuilder(id, bytes);
}