// Code generated by proto watcher. DO NOT EDIT.

import 'package:libcli/command/command.dart';
import 'package:libcli/pb/pb.dart' as pb;

pb.Object objectBuilder(int id, List<int> bytes) {
    switch (id) {
    }
    throw Exception('failed to create object in SysService. id($id) out of range');
}

class SysService extends Service {

  /// init sys service with predefine remote url
  /// remote url is defined in "service project/proto/.proto.json"
  /// For example:
  ///
  ///     final service = SysService(sender: (BuildContext ctx, pb.Object command) async {
  ///         return StringResponse()..value = 'fake';
  ///     });
  ///
  SysService({Sender? sender}): super('sys', sender: sender);

  @override
  pb.Object newObjectByID(int id, List<int> bytes) => objectBuilder(id, bytes);
}