// Code generated by proto watcher. DO NOT EDIT.

import 'package:libcli/net/net.dart' as net;
import 'sync.pb.dart';
import 'word.pb.dart';
import 'file.pb.dart';

  net.Object objectBuilder(int id, List<int> bytes) {
    switch (id) {
      case 8:
        return Sync.fromBuffer(bytes);
      case 9:
        return Word.fromBuffer(bytes);
      case 10:
        return File.fromBuffer(bytes);
    }
    throw Exception('failed to create object in objectBuilder. id($id) out of range');
}
